/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      colors: {
        background: 'var(--background)',
        surface: 'var(--surface)',
        'surface-bright': 'var(--surface-bright)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-variant': 'var(--surface-variant)',
        'on-background': 'var(--on-background)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        outline: 'var(--outline)',
        'outline-variant': 'var(--outline-variant)',
        primary: 'var(--primary)',
        'on-primary': 'var(--on-primary)',
        secondary: 'var(--secondary)',
        'on-secondary': 'var(--on-secondary)',
        'secondary-container': 'var(--secondary-container)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
        'surface-tint': 'var(--surface-tint)',
        'on-tertiary': 'var(--on-tertiary)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        error: 'var(--error)',
        'on-error': 'var(--on-error)',
        'error-container': 'var(--error-container)',
        'on-error-container': 'var(--on-error-container)',
        owned: 'var(--owned)',
        'on-owned': 'var(--on-owned)',
        duplicate: 'var(--duplicate)',
        'on-duplicate': 'var(--on-duplicate)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        gutter: '16px',
        'sticker-size': '96px',
        'max-width': '1100px',
        'margin-desktop': '32px',
        'margin-mobile': '16px',
      },
      maxWidth: {
        'max-width': '1100px',
      },
      fontSize: {
        'display-xl': ['56px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-l': ['36px', { lineHeight: '1.2', letterSpacing: '-0.03em', fontWeight: '700' }],
        heading: ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-strong': ['15px', { lineHeight: '22px', fontWeight: '600' }],
        body: ['15px', { lineHeight: '22px', fontWeight: '400' }],
        small: ['13px', { lineHeight: '18px', fontWeight: '500' }],
        caps: ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '600' }],
        'mono-code': ['13px', { lineHeight: '1', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
